export const GRAFANA_PANELS = {
  operations: {
    totalRuns: 1,
    lastDuration: 2,
    avgDurationP50: 3,
    errorCount: 4,
    newArticles: 5,
    duplicateRate: 6,
    failedArticles: 7,
    newPerRun: 8,
    articleVolumeTimeline: 9,
    runDurationTimeline: 10,
    newBySource: 11,
    errorsByType: 12,
  },
  logs: {
    logVolumeByLevel: 1,
    errorCount1h: 2,
    warningCount1h: 3,
    executionTimeline: 4,
    errorLogs: 5,
    articleSuccessLogs: 6,
    articleFailureLogs: 7,
  },
  traces: {
    totalTraces: 1,
    llmLatencyP95: 2,
    errorSpans: 3,
    spanRateTimeline: 4,
    recentTraces: 5,
  },
} as const
