"""Exports the backend's OpenAPI contract to a static, checked-in file, and reports
which endpoints aren't yet fully covered by it — the source the frontend's generated
types (`frontend/lib/api/generated-types.ts`) are produced from (026-rate-limit-codegen).

Imports `backend.main.app` directly and calls `app.openapi()` rather than hitting a
live server: deterministic, no running backend required (research.md Decision 6).

Output:
  - backend/openapi.json            — app.openapi(), sorted keys for stable diffs
  - backend/openapi-coverage-gap.md — endpoints whose request and/or response body
                                       isn't backed by a defined Pydantic schema
                                       (FR-013) — tracked as follow-up, not a build
                                       failure.
"""
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
OPENAPI_JSON_PATH = REPO_ROOT / "backend" / "openapi.json"
COVERAGE_GAP_PATH = REPO_ROOT / "backend" / "openapi-coverage-gap.md"

_OPERATION_METHODS = {"get", "post", "put", "patch", "delete"}


def _resolve_schema(schema: dict, components: dict) -> dict:
    """Follows a single {"$ref": "#/components/schemas/X"} indirection."""
    if not schema:
        return {}
    ref = schema.get("$ref")
    if not ref:
        return schema
    name = ref.rsplit("/", 1)[-1]
    return components.get("schemas", {}).get(name, {})


def _is_untyped(schema: dict, components: dict) -> bool:
    """True when a request/response schema carries no usable field information for
    codegen — e.g. a bare `dict` request body (`type: object`, no `properties`)."""
    resolved = _resolve_schema(schema, components)
    if not resolved:
        return True
    return resolved.get("type") == "object" and not resolved.get("properties")


def build_openapi_schema() -> dict:
    from backend.main import app

    # Force a full rebuild rather than FastAPI's own post-first-call cache, so two
    # separate invocations of this function within one process are each a genuine
    # regeneration (not a cache hit) — see scripts/tests/test_export_openapi_schema.py's
    # idempotency test.
    app.openapi_schema = None
    return app.openapi()


def find_coverage_gaps(openapi_schema: dict) -> list[dict[str, Any]]:
    """One entry per (path, method) whose request body and/or every success response
    isn't backed by a defined schema — informational, not a build failure (FR-013)."""
    components = openapi_schema.get("components", {})
    gaps: list[dict[str, Any]] = []

    for path, operations in openapi_schema.get("paths", {}).items():
        for method, operation in operations.items():
            if method not in _OPERATION_METHODS:
                continue
            reasons = []

            request_body = operation.get("requestBody")
            if request_body:
                content = request_body.get("content", {}).get("application/json", {})
                if _is_untyped(content.get("schema", {}), components):
                    reasons.append("request body has no defined schema")

            success_responses = [
                resp for code, resp in operation.get("responses", {}).items()
                if code.startswith("2")
            ]
            response_bodies = [
                resp["content"]["application/json"]
                for resp in success_responses
                if "application/json" in resp.get("content", {})
            ]
            if response_bodies and all(
                _is_untyped(body.get("schema", {}), components) for body in response_bodies
            ):
                reasons.append("response body has no defined schema")

            if reasons:
                gaps.append({"path": path, "method": method.upper(), "reasons": reasons})

    gaps.sort(key=lambda g: (g["path"], g["method"]))
    return gaps


def render_coverage_gap_report(gaps: list[dict[str, Any]]) -> str:
    lines = [
        "# OpenAPI Type-Generation Coverage Gaps",
        "",
        "Auto-generated by `scripts/export_openapi_schema.py` — do not hand-edit.",
        "Endpoints listed here are excluded from frontend type generation "
        "(specs/026-rate-limit-codegen FR-013) until their request/response schema is "
        "fully defined with a Pydantic model. Their `frontend/lib/api/*.ts` counterpart "
        "keeps its current hand-written type until then.",
        "",
    ]
    if not gaps:
        lines.append("None — every endpoint has a fully defined request/response schema.")
    else:
        for gap in gaps:
            lines.append(f"- `{gap['method']} {gap['path']}` — {', '.join(gap['reasons'])}")
    return "\n".join(lines) + "\n"


def main() -> None:
    schema = build_openapi_schema()
    OPENAPI_JSON_PATH.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    gaps = find_coverage_gaps(schema)
    COVERAGE_GAP_PATH.write_text(render_coverage_gap_report(gaps), encoding="utf-8")

    print(f"Wrote {OPENAPI_JSON_PATH.relative_to(REPO_ROOT)}")
    print(f"Wrote {COVERAGE_GAP_PATH.relative_to(REPO_ROOT)} ({len(gaps)} gap(s))")


if __name__ == "__main__":
    main()
    sys.exit(0)
