"""One-shot: split the old secrets/{shared,staging,production}.tfvars into the
github-*/railway-* pair the Terraform / Railway-CLI split expects.

    python scripts/split_tfvars.py            # writes the 6 new files, keeps the old 3
    python scripts/split_tfvars.py --delete   # also removes the old 3 afterwards

Terraform (github-ci.tf) reads only github-{shared,<env>}.tfvars; everything else
goes to railway-{shared,<env>}.tfvars for scripts/push_railway_variables.py.
Comments are dropped (the *.tfvars.example files carry the docs);
`railway_environment_id` is dropped entirely (nothing uses it any more).
"""
import re
import shutil
import subprocess
import sys
from pathlib import Path

SECRETS = Path(__file__).resolve().parent.parent / "infra" / "terraform" / "railway" / "secrets"

GITHUB_KEYS = {
    "github_owner", "github_repository", "app_env",
    "gh_claude_api_key", "gh_codecov_token", "gh_gemini_api_key", "gh_gist_id",
    "gh_gist_secret", "gh_nextauth_secret", "gh_npm_token", "gh_openrouter_api_key",
    "gh_release_pat", "gh_var_backend_url", "gh_var_storybook_url",
    "gh_env_database_url", "gh_env_railway_token", "gh_env_frontend_url",
} | {f"service_id_{s}" for s in (
    "dashboard_backend", "dashboard_frontend", "storybook", "scrape_and_analyze",
    "chatbot_plugin", "fastembed", "weekly_report", "refresh_metrics",
    "rag_backfill", "dedup_reconcile",
)}
DROP_KEYS = {"railway_environment_id"}

LINE_RE = re.compile(r'^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?)\s*$')


def _split_one(layer):
    src = SECRETS / f"{layer}.tfvars"
    if not src.is_file():
        print(f"skip: {src} not found")
        return
    gh, rw = [], []
    for line in src.read_text(encoding="utf-8").splitlines():
        m = LINE_RE.match(line)
        if not m or line.lstrip().startswith("#"):
            continue
        key, rhs = m.group(1), m.group(2)
        if key in DROP_KEYS:
            continue
        (gh if key in GITHUB_KEYS else rw).append(f"{key} = {rhs}")
    hdr = f"# Generated by scripts/split_tfvars.py from {src.name}. Fill/verify against the *.example.\n"
    (SECRETS / f"github-{layer}.tfvars").write_text(hdr + "\n".join(gh) + "\n", encoding="utf-8")
    (SECRETS / f"railway-{layer}.tfvars").write_text(hdr + "\n".join(rw) + "\n", encoding="utf-8")
    print(f"{src.name}: {len(gh)} -> github-{layer}.tfvars, {len(rw)} -> railway-{layer}.tfvars")


def main():
    for layer in ("shared", "staging", "production"):
        _split_one(layer)
    if "--delete" in sys.argv:
        for layer in ("shared", "staging", "production"):
            p = SECRETS / f"{layer}.tfvars"
            if p.is_file():
                p.unlink()
                print(f"removed {p.name}")
    tf = shutil.which("terraform")
    if tf:  # align `=` so `terraform fmt -check` (Makefile / terraform.yml) passes
        subprocess.run([tf, "fmt", str(SECRETS)], check=False)
    print("\nNext: eyeball the 6 files, then `make push-tfvars`.")


if __name__ == "__main__":
    main()
